server:
  port: 8031

eureka:
  client:
    serviceUrl:
      defaultZone: http://${EUREKA_ZONE_HOST:localhost}:${EUREKA_ZONE_PORT:8761}/eureka/

spring:
  application:
    name: turbine
  rabbitmq:
    host: ${RABBIT_MQ_HOST:132.224.44.83}
    port: ${RABBIT_MQ_PORT:5672}
    username: ${RABBIT_MQ_USERNAME:guest}
    password: ${RABBIT_MQ_PASSWORD:guest}
#    virtualHost: /test
#  cloud:
#    stream:
#      rabbit:
#        bindings:
#          test:
#            consumer:
#              prefix: z
#  cloud:
#    stream:
#      bindings:
#        input:
#          group: default

turbine:
  stream:
    port: 8030

management:
  server:
    port: 8030
  endpoints:
    web:
      exposure:
        include: '*'

logging:
  level:
    org.springframework.web: debug
  path: logs/
  file:
    max-size: 1GB